#!/bin/sh
### Bedrock Linux 1.0alpha3 Bosco
### brs (BedRock Setup)

# sets up or takes down share points for client in argument

mountcmd="mount --bind"

# check for need to print help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
	echo "Usage: brs [-r] [CLIENTS]"
	echo ""
	echo "brs will set up (or take down with the -r argument) the share bind"
	echo "mounts for the clients mentioned as arguments."
	exit 0
fi

# ensure running in core bedrock - anywhere else will set up mounts in the
# wrong place.

if [ "$(bri -n)" != "bedrock" ]
then
	echo "Must run in core Bedrock, not a client. Try running:"
	echo "brc bedrock brs $@"
	exit 1
fi

if test x"$1" = "x-r"; then
	mountcmd="umount -l"
	shift
fi

RESULT=0
for CLIENT in "$@"
do
	DIRECTORY=$(bri -p $CLIENT)
	if [ -z "$DIRECTORY" ]
	then
		echo "ERROR: Cannot find $CLIENT"
	else
		for SHARE in $(bri -s $CLIENT)
		do
			TRYMOUNT=/bin/true
			if mountpoint -q $DIRECTORY$SHARE && \
				test "$mountcmd" = "mount --bind"
			then
				TRYMOUNT=/bin/false
			if [ -d $SHARE ] && [ ! -d $DIRECTORY$SHARE ]
			then
				mkdir -p $DIRECTORY$SHARE
			elif [ -f $SHARE ] && [ ! -f $DIRECTORY$SHARE ]
			then
				touch $DIRECTORY$SHARE
			elif [ ! -d $SHARE ] && [ -d $DIRECTORY$SHARE ]
			then
				mkdir -p $SHARE
			elif [ ! -f $SHARE ] && [ -f $DIRECTORY$SHARE ]
			then
				touch $SHARE
			elif [ ! -e $SHARE ] || [ ! -e $DIRECTORY$SHARE ]
			then
				TRYMOUNT=/bin/false
				RESULT=2
				echo "ERROR: Cannot share $SHARE in $DIRECTORY"
				echo "Do both $SHARE and $DIRECTORY$SHARE exist?"
			fi
			if $TRYMOUNT
			then
				$mountcmd $SHARE $DIRECTORY$SHARE || RESULT=1
			fi
		done
	fi
done
exit $RESULT
